apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: the-gates-pro
  namespace: numinia
  annotations:
    reconcile.fluxcd.io/requestedAt: "1734523452"
spec:
  interval: 5m
  releaseName: the-gates-pro
  targetNamespace: numinia
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./clusters/prod-cluster/base/hyperfy2
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: the-gates-pro-values
      valuesKey: values.yaml