apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-numinia-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "notifications@numengames.com"
    privateKeySecretRef:
      name: letsencrypt-numinia-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-art-unchained-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "notifications@numengames.com"
    privateKeySecretRef:
      name: letsencrypt-art-unchained-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-numen-games-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "notifications@numengames.com"
    privateKeySecretRef:
      name: letsencrypt-numen-games-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-active-inference-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "notifications@numengames.com"
    privateKeySecretRef:
      name: letsencrypt-active-inference-prod
    solvers:
    - http01:
        ingress:
          class: traefik