{{- if .Values.domainMapping.enabled }}
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: {{ .Values.domainMapping.hostname }}
  namespace: {{ .Values.namespace | default .Values.orgName }}
  annoatations: 
    kourier.knative.dev/disable-http2: "true"
spec:
  ref:
    name: hyperfy2-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}
    kind: Service
    apiVersion: serving.knative.dev/v1
{{- end }}
