apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-creator-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: secret-creator-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-creator-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: secret-creator-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}
        environment: {{ .Values.environment }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: dummy
          image: alpine
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets-hyperfy2-{{ .Values.orgName }}-{{ .Values.appName }}-{{ .Values.environment }}