apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multiplex-pro
  namespace: numinia
  annotations:
    reconcile.fluxcd.io/requestedAt: "1746007720"
spec:
  interval: 5m
  releaseName: multiplex-pro
  targetNamespace: numinia
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./clusters/prod-cluster/base/hyperfy2
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: multiplex-pro-values
      valuesKey: values.yaml 